// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: chapters.sql

package main

import (
	"context"
)

const calcMaxSequence = `-- name: CalcMaxSequence :one
SELECT MAX(sequence) AS max_sequence FROM chapters
WHERE book_id = ? AND parent_id = ? AND deleted_at IS NULL
`

type CalcMaxSequenceParams struct {
	BookID   *int64 `json:"book_id"`
	ParentID *int64 `json:"parent_id"`
}

func (q *Queries) CalcMaxSequence(ctx context.Context, arg CalcMaxSequenceParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, calcMaxSequence, arg.BookID, arg.ParentID)
	var max_sequence interface{}
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const calcNextSequence = `-- name: CalcNextSequence :many
SELECT sequence FROM chapters
WHERE book_id = ? AND parent_id = ?  AND deleted_at IS NULL
AND sequence > ?
ORDER BY sequence
LIMIT 1
`

type CalcNextSequenceParams struct {
	BookID   *int64   `json:"book_id"`
	ParentID *int64   `json:"parent_id"`
	Sequence *float64 `json:"sequence"`
}

func (q *Queries) CalcNextSequence(ctx context.Context, arg CalcNextSequenceParams) ([]*float64, error) {
	rows, err := q.db.QueryContext(ctx, calcNextSequence, arg.BookID, arg.ParentID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*float64
	for rows.Next() {
		var sequence *float64
		if err := rows.Scan(&sequence); err != nil {
			return nil, err
		}
		items = append(items, sequence)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calcPrevSequence = `-- name: CalcPrevSequence :many
SELECT sequence FROM chapters
WHERE book_id = ? AND parent_id = ?  AND deleted_at IS NULL
AND sequence < ?
ORDER BY sequence DESC
LIMIT 1
`

type CalcPrevSequenceParams struct {
	BookID   *int64   `json:"book_id"`
	ParentID *int64   `json:"parent_id"`
	Sequence *float64 `json:"sequence"`
}

func (q *Queries) CalcPrevSequence(ctx context.Context, arg CalcPrevSequenceParams) ([]*float64, error) {
	rows, err := q.db.QueryContext(ctx, calcPrevSequence, arg.BookID, arg.ParentID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*float64
	for rows.Next() {
		var sequence *float64
		if err := rows.Scan(&sequence); err != nil {
			return nil, err
		}
		items = append(items, sequence)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters ( book_id, name, content, parent_id, sequence
) VALUES ( ?, ?, ?, ?, ?
)
RETURNING id, name, book_id, parent_id, sequence, content, created_at, updated_at, deleted_at
`

type CreateChapterParams struct {
	BookID   *int64   `json:"book_id"`
	Name     *string  `json:"name"`
	Content  *string  `json:"content"`
	ParentID *int64   `json:"parent_id"`
	Sequence *float64 `json:"sequence"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, createChapter,
		arg.BookID,
		arg.Name,
		arg.Content,
		arg.ParentID,
		arg.Sequence,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BookID,
		&i.ParentID,
		&i.Sequence,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteChapter = `-- name: DeleteChapter :exec
UPDATE chapters
SET deleted_at = datetime('now')
WHERE id = ?
`

func (q *Queries) DeleteChapter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChapter, id)
	return err
}

const deleteChapters = `-- name: DeleteChapters :exec
UPDATE chapters
SET deleted_at = datetime('now')
WHERE book_id = ?
`

func (q *Queries) DeleteChapters(ctx context.Context, bookID *int64) error {
	_, err := q.db.ExecContext(ctx, deleteChapters, bookID)
	return err
}

const getChapter = `-- name: GetChapter :one
SELECT id, name, book_id, parent_id, sequence, content, created_at, updated_at, deleted_at FROM chapters WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetChapter(ctx context.Context, id int64) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BookID,
		&i.ParentID,
		&i.Sequence,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChapters = `-- name: ListChapters :many
SELECT id, name, book_id, parent_id, sequence, content, created_at, updated_at, deleted_at FROM chapters
WHERE book_id = ?
AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListChapters(ctx context.Context, bookID *int64) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChapters, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chapter
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BookID,
			&i.ParentID,
			&i.Sequence,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE chapters
SET name = coalesce(@name, name),
    sequence = coalesce(@sequence, sequence),
    content = coalesce(@content, content),
    parent_id = coalesce(@parent_id, parent_id)
WHERE id = ?
RETURNING id, name, book_id, parent_id, sequence, content, created_at, updated_at, deleted_at
`

type UpdateChapterParams struct {
	Name     *string  `json:"name"`
	Sequence *float64 `json:"sequence"`
	Content  *string  `json:"content"`
	ParentID *int64   `json:"parent_id"`
	ID       int64    `json:"id"`
}

func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, updateChapter,
		arg.Name,
		arg.Sequence,
		arg.Content,
		arg.ParentID,
		arg.ID,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BookID,
		&i.ParentID,
		&i.Sequence,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
