// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Book struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Author    sql.NullString `json:"author"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Summary   sql.NullString `json:"summary"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Chapter struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	BookID    int64          `json:"book_id"`
	Content   sql.NullString `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
