// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CreateBook(arg1:string):Promise<db.Book>;

export function Greet(arg1:string):Promise<string>;

export function ListBooks(arg1:number):Promise<Array<db.Book>>;
