// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['main']['App']['CreateBook'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBookWithChapters(arg1) {
  return window['go']['main']['App']['GetBookWithChapters'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListBooks(arg1) {
  return window['go']['main']['App']['ListBooks'](arg1);
}

export function ListChapters(arg1) {
  return window['go']['main']['App']['ListChapters'](arg1);
}

export function UpdateChapter(arg1) {
  return window['go']['main']['App']['UpdateChapter'](arg1);
}
