// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBook(arg1:string):Promise<main.Book>;

export function DeleteBook(arg1:number):Promise<Error>;

export function GetBook(arg1:number):Promise<main.Book>;

export function GetBookWithChapters(arg1:number):Promise<main.BookWithChapters>;

export function Greet(arg1:string):Promise<string>;

export function ListBooks(arg1:number):Promise<Array<main.Book>>;

export function ListChapters(arg1:number):Promise<Array<main.Chapter>>;
