// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['main']['App']['CreateBook'](arg1);
}

export function CreateChapter(arg1) {
  return window['go']['main']['App']['CreateChapter'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBookWithChapters(arg1) {
  return window['go']['main']['App']['GetBookWithChapters'](arg1);
}

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertChapterAfter(arg1, arg2) {
  return window['go']['main']['App']['InsertChapterAfter'](arg1, arg2);
}

export function ListBooks(arg1) {
  return window['go']['main']['App']['ListBooks'](arg1);
}

export function ListChapters(arg1) {
  return window['go']['main']['App']['ListChapters'](arg1);
}

export function MoveChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveChapter'](arg1, arg2, arg3);
}

export function PublishBook(arg1, arg2) {
  return window['go']['main']['App']['PublishBook'](arg1, arg2);
}

export function RenderMarkdown(arg1) {
  return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function SelectCover() {
  return window['go']['main']['App']['SelectCover']();
}

export function UpdateChapter(arg1) {
  return window['go']['main']['App']['UpdateChapter'](arg1);
}

export function UploadImage(arg1) {
  return window['go']['main']['App']['UploadImage'](arg1);
}
